# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_w_main.ui'
#
# Created: Mon Mar 06 14:34:28 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(464, 390)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 441, 213))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.TAB_measurement = QtGui.QWidget()
        self.TAB_measurement.setObjectName(_fromUtf8("TAB_measurement"))
        self.BTN_measureBL = QtGui.QPushButton(self.TAB_measurement)
        self.BTN_measureBL.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.BTN_measureBL.setObjectName(_fromUtf8("BTN_measureBL"))
        self.BTN_measureh = QtGui.QPushButton(self.TAB_measurement)
        self.BTN_measureh.setEnabled(False)
        self.BTN_measureh.setGeometry(QtCore.QRect(10, 130, 111, 23))
        self.BTN_measureh.setObjectName(_fromUtf8("BTN_measureh"))
        self.BTN_weighMass = QtGui.QPushButton(self.TAB_measurement)
        self.BTN_weighMass.setGeometry(QtCore.QRect(10, 70, 111, 23))
        self.BTN_weighMass.setObjectName(_fromUtf8("BTN_weighMass"))
        self.label_4 = QtGui.QLabel(self.TAB_measurement)
        self.label_4.setGeometry(QtCore.QRect(140, 130, 281, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.TAB_measurement)
        self.label_5.setGeometry(QtCore.QRect(140, 70, 281, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.TAB_measurement)
        self.label_6.setGeometry(QtCore.QRect(140, 10, 281, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.TAB_measurement)
        self.label_7.setGeometry(QtCore.QRect(140, 150, 281, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.TAB_measurement, _fromUtf8(""))
        self.TAB_calibration = QtGui.QWidget()
        self.TAB_calibration.setObjectName(_fromUtf8("TAB_calibration"))
        self.BTN_PID = QtGui.QPushButton(self.TAB_calibration)
        self.BTN_PID.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.BTN_PID.setObjectName(_fromUtf8("BTN_PID"))
        self.label_2 = QtGui.QLabel(self.TAB_calibration)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 301, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.BTN_cfgPos = QtGui.QPushButton(self.TAB_calibration)
        self.BTN_cfgPos.setGeometry(QtCore.QRect(10, 100, 111, 23))
        self.BTN_cfgPos.setObjectName(_fromUtf8("BTN_cfgPos"))
        self.BTN_velocitymode = QtGui.QPushButton(self.TAB_calibration)
        self.BTN_velocitymode.setGeometry(QtCore.QRect(10, 140, 111, 23))
        self.BTN_velocitymode.setObjectName(_fromUtf8("BTN_velocitymode"))
        self.BTN_cfgShadowSensor = QtGui.QPushButton(self.TAB_calibration)
        self.BTN_cfgShadowSensor.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.BTN_cfgShadowSensor.setObjectName(_fromUtf8("BTN_cfgShadowSensor"))
        self.label_8 = QtGui.QLabel(self.TAB_calibration)
        self.label_8.setGeometry(QtCore.QRect(130, 50, 301, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.TAB_calibration)
        self.label_9.setGeometry(QtCore.QRect(130, 100, 301, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_16 = QtGui.QLabel(self.TAB_calibration)
        self.label_16.setGeometry(QtCore.QRect(130, 140, 301, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.TAB_calibration)
        self.label_17.setGeometry(QtCore.QRect(130, 70, 301, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.TAB_calibration)
        self.label_18.setGeometry(QtCore.QRect(130, 160, 301, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget.addTab(self.TAB_calibration, _fromUtf8(""))
        self.TAB_settings = QtGui.QWidget()
        self.TAB_settings.setObjectName(_fromUtf8("TAB_settings"))
        self.BTN_PathAndVariables = QtGui.QPushButton(self.TAB_settings)
        self.BTN_PathAndVariables.setGeometry(QtCore.QRect(10, 70, 111, 23))
        self.BTN_PathAndVariables.setObjectName(_fromUtf8("BTN_PathAndVariables"))
        self.BTN_dataAcq = QtGui.QPushButton(self.TAB_settings)
        self.BTN_dataAcq.setGeometry(QtCore.QRect(10, 40, 111, 23))
        self.BTN_dataAcq.setObjectName(_fromUtf8("BTN_dataAcq"))
        self.BTN_ChooseDevice = QtGui.QPushButton(self.TAB_settings)
        self.BTN_ChooseDevice.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.BTN_ChooseDevice.setObjectName(_fromUtf8("BTN_ChooseDevice"))
        self.BTN_CoilPolarities = QtGui.QPushButton(self.TAB_settings)
        self.BTN_CoilPolarities.setGeometry(QtCore.QRect(10, 100, 111, 23))
        self.BTN_CoilPolarities.setObjectName(_fromUtf8("BTN_CoilPolarities"))
        self.BTN_Debugging = QtGui.QPushButton(self.TAB_settings)
        self.BTN_Debugging.setGeometry(QtCore.QRect(10, 130, 111, 23))
        self.BTN_Debugging.setObjectName(_fromUtf8("BTN_Debugging"))
        self.BTN_FactoryReset = QtGui.QPushButton(self.TAB_settings)
        self.BTN_FactoryReset.setGeometry(QtCore.QRect(10, 160, 111, 23))
        self.BTN_FactoryReset.setObjectName(_fromUtf8("BTN_FactoryReset"))
        self.label_3 = QtGui.QLabel(self.TAB_settings)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 301, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_10 = QtGui.QLabel(self.TAB_settings)
        self.label_10.setGeometry(QtCore.QRect(130, 40, 301, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.TAB_settings)
        self.label_11.setGeometry(QtCore.QRect(130, 70, 301, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.TAB_settings)
        self.label_12.setGeometry(QtCore.QRect(130, 100, 301, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.TAB_settings)
        self.label_13.setGeometry(QtCore.QRect(130, 130, 301, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.TAB_settings)
        self.label_14.setGeometry(QtCore.QRect(130, 160, 301, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.TAB_settings, _fromUtf8(""))
        self.TAB_about = QtGui.QWidget()
        self.TAB_about.setObjectName(_fromUtf8("TAB_about"))
        self.tabWidget.addTab(self.TAB_about, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 151, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.BTN_current = QtGui.QPushButton(self.groupBox)
        self.BTN_current.setGeometry(QtCore.QRect(10, 110, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.BTN_current.setFont(font)
        self.BTN_current.setObjectName(_fromUtf8("BTN_current"))
        self.BTN_coilposition = QtGui.QPushButton(self.groupBox)
        self.BTN_coilposition.setGeometry(QtCore.QRect(10, 23, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.BTN_coilposition.setFont(font)
        self.BTN_coilposition.setObjectName(_fromUtf8("BTN_coilposition"))
        self.BTN_voltageacrosscoils = QtGui.QPushButton(self.groupBox)
        self.BTN_voltageacrosscoils.setGeometry(QtCore.QRect(10, 81, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.BTN_voltageacrosscoils.setFont(font)
        self.BTN_voltageacrosscoils.setObjectName(_fromUtf8("BTN_voltageacrosscoils"))
        self.BTN_coilvelocities = QtGui.QPushButton(self.groupBox)
        self.BTN_coilvelocities.setGeometry(QtCore.QRect(10, 52, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.BTN_coilvelocities.setFont(font)
        self.BTN_coilvelocities.setObjectName(_fromUtf8("BTN_coilvelocities"))
        self.TXT_coilPosition = QtGui.QLabel(self.groupBox)
        self.TXT_coilPosition.setEnabled(False)
        self.TXT_coilPosition.setGeometry(QtCore.QRect(90, 20, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.TXT_coilPosition.setPalette(palette)
        self.TXT_coilPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.TXT_coilPosition.setObjectName(_fromUtf8("TXT_coilPosition"))
        self.TXT_coilVelocities = QtGui.QLabel(self.groupBox)
        self.TXT_coilVelocities.setEnabled(False)
        self.TXT_coilVelocities.setGeometry(QtCore.QRect(90, 50, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.TXT_coilVelocities.setPalette(palette)
        self.TXT_coilVelocities.setAlignment(QtCore.Qt.AlignCenter)
        self.TXT_coilVelocities.setObjectName(_fromUtf8("TXT_coilVelocities"))
        self.TXT_coilVoltage = QtGui.QLabel(self.groupBox)
        self.TXT_coilVoltage.setEnabled(False)
        self.TXT_coilVoltage.setGeometry(QtCore.QRect(90, 80, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.TXT_coilVoltage.setPalette(palette)
        self.TXT_coilVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.TXT_coilVoltage.setObjectName(_fromUtf8("TXT_coilVoltage"))
        self.TXT_current = QtGui.QLabel(self.groupBox)
        self.TXT_current.setEnabled(False)
        self.TXT_current.setGeometry(QtCore.QRect(90, 110, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 194, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.TXT_current.setPalette(palette)
        self.TXT_current.setAlignment(QtCore.Qt.AlignCenter)
        self.TXT_current.setObjectName(_fromUtf8("TXT_current"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 230, 151, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.RB_coilA = QtGui.QRadioButton(self.groupBox_2)
        self.RB_coilA.setGeometry(QtCore.QRect(80, 30, 82, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.RB_coilA.setFont(font)
        self.RB_coilA.setObjectName(_fromUtf8("RB_coilA"))
        self.RB_coilB = QtGui.QRadioButton(self.groupBox_2)
        self.RB_coilB.setGeometry(QtCore.QRect(80, 50, 82, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.RB_coilB.setFont(font)
        self.RB_coilB.setObjectName(_fromUtf8("RB_coilB"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 110, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.TXT_BLCoil = QtGui.QLabel(self.groupBox_2)
        self.TXT_BLCoil.setGeometry(QtCore.QRect(110, 70, 31, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.TXT_BLCoil.setFont(font)
        self.TXT_BLCoil.setObjectName(_fromUtf8("TXT_BLCoil"))
        self.TXT_weighingCoil = QtGui.QLabel(self.groupBox_2)
        self.TXT_weighingCoil.setGeometry(QtCore.QRect(110, 100, 31, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.TXT_weighingCoil.setFont(font)
        self.TXT_weighingCoil.setObjectName(_fromUtf8("TXT_weighingCoil"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 230, 121, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(15, 20, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.TXT_activeMode = QtGui.QLabel(self.groupBox_3)
        self.TXT_activeMode.setGeometry(QtCore.QRect(40, 40, 51, 31))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.TXT_activeMode.setFont(font)
        self.TXT_activeMode.setObjectName(_fromUtf8("TXT_activeMode"))
        self.BTN_manualBalancecontrol = QtGui.QPushButton(self.groupBox_3)
        self.BTN_manualBalancecontrol.setGeometry(QtCore.QRect(10, 90, 101, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.BTN_manualBalancecontrol.setFont(font)
        self.BTN_manualBalancecontrol.setObjectName(_fromUtf8("BTN_manualBalancecontrol"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LEGO Watt-Balance", None))
        self.BTN_measureBL.setText(_translate("MainWindow", "Measure BL", None))
        self.BTN_measureh.setText(_translate("MainWindow", "Measure h", None))
        self.BTN_weighMass.setText(_translate("MainWindow", "Weigh Mass", None))
        self.label_4.setText(_translate("MainWindow", "Try to measure Planck\'s Constant, and see how close", None))
        self.label_5.setText(_translate("MainWindow", "Weigh a Mass", None))
        self.label_6.setText(_translate("MainWindow", "Start velocity mode to measure BL at zero position", None))
        self.label_7.setText(_translate("MainWindow", "you are to the latest values.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_measurement), _translate("MainWindow", "Measurement", None))
        self.BTN_PID.setText(_translate("MainWindow", "Configure static PID", None))
        self.label_2.setText(_translate("MainWindow", "Modify the control loop which is used to stabilize the balance", None))
        self.BTN_cfgPos.setText(_translate("MainWindow", "Configure Position", None))
        self.BTN_velocitymode.setText(_translate("MainWindow", "Configure Velomode", None))
        self.BTN_cfgShadowSensor.setText(_translate("MainWindow", "Configure Shadow S.", None))
        self.label_8.setText(_translate("MainWindow", "Set the balance\'s zero position and determine where ", None))
        self.label_9.setText(_translate("MainWindow", "Calibrate the shadow-sensor voltage to millimeter conversion", None))
        self.label_16.setText(_translate("MainWindow", "Modify the control loop used in velo mode and customize ", None))
        self.label_17.setText(_translate("MainWindow", "the correlation shadow-sensor to position is linear. ", None))
        self.label_18.setText(_translate("MainWindow", "the sine wave used to drive the balance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_calibration), _translate("MainWindow", "Calibration", None))
        self.BTN_PathAndVariables.setText(_translate("MainWindow", "Paths and Variables", None))
        self.BTN_dataAcq.setText(_translate("MainWindow", "Data Acquisition", None))
        self.BTN_ChooseDevice.setText(_translate("MainWindow", "Choose Device", None))
        self.BTN_CoilPolarities.setText(_translate("MainWindow", "Coil Polarities", None))
        self.BTN_Debugging.setText(_translate("MainWindow", "Debugging", None))
        self.BTN_FactoryReset.setText(_translate("MainWindow", "Factory reset", None))
        self.label_3.setText(_translate("MainWindow", "Choose another Device in your System", None))
        self.label_10.setText(_translate("MainWindow", "Customize the Data Acquisition Parameters", None))
        self.label_11.setText(_translate("MainWindow", "Adjust File Path, and Variables depending on your Setup", None))
        self.label_12.setText(_translate("MainWindow", "Set the polarities for your Wattbalance coils", None))
        self.label_13.setText(_translate("MainWindow", "Get some more information to debugg your system", None))
        self.label_14.setText(_translate("MainWindow", "Reset everything to default", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_settings), _translate("MainWindow", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_about), _translate("MainWindow", "About", None))
        self.groupBox.setTitle(_translate("MainWindow", "Graphs:", None))
        self.BTN_current.setText(_translate("MainWindow", "Current", None))
        self.BTN_coilposition.setText(_translate("MainWindow", "Coil position", None))
        self.BTN_voltageacrosscoils.setText(_translate("MainWindow", "Voltage in coils", None))
        self.BTN_coilvelocities.setText(_translate("MainWindow", "Coil velocities", None))
        self.TXT_coilPosition.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Open</span></p></body></html>", None))
        self.TXT_coilVelocities.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Open</span></p></body></html>", None))
        self.TXT_coilVoltage.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Open</span></p></body></html>", None))
        self.TXT_current.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Open</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Coil Info:", None))
        self.RB_coilA.setText(_translate("MainWindow", "Coil A", None))
        self.RB_coilB.setText(_translate("MainWindow", "Coil B", None))
        self.label_15.setText(_translate("MainWindow", "Active Coil:", None))
        self.label_19.setText(_translate("MainWindow", "Measuring BL on:", None))
        self.label_21.setText(_translate("MainWindow", "Weighing on:", None))
        self.TXT_BLCoil.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">A/B</span></p></body></html>", None))
        self.TXT_weighingCoil.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">A/B</span></p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mode Info:", None))
        self.label_20.setText(_translate("MainWindow", "Mode:", None))
        self.TXT_activeMode.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">S/V/M</p></body></html>", None))
        self.BTN_manualBalancecontrol.setText(_translate("MainWindow", "Manual Control", None))

